version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: interview360-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r5t
      POSTGRES_DB: Interview360Db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview360-network

  redis:
    image: redis:latest
    container_name: interview360-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - interview360-network

volumes:
  postgres_data:
  redis_data:

networks:
  interview360-network:
    driver: bridge 